name: pf-animations-demo

on:
  push:
    branches: [ demo/pf-animations ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Quay.io
      uses: docker/login-action@v3
      with:
        registry: quay.io
        username: jenny-s51
        password: ${{ secrets.QUAY_PASSWORD }}

    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: quay.io/jenny-s51/odh-dashboard:pf-animations-demo
        cache-from: type=gha
        cache-to: type=gha,mode=max
